// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbzqpobbruunivnjwjud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdienFwb2JicnV1bml2bmp3anVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1ODcxNzMsImV4cCI6MjA3MzE2MzE3M30.2-KKp-kGurtQLddI-ulcXpOUrreHDbL-YxQAF4vCbn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});